// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Builder: typeof import('./src/views/changduan/builder/index.vue')['default']
    Changduan: typeof import('./src/views/changduan/index.vue')['default']
    ChangDuanForm: typeof import('./src/components/ChangDuanForm.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    Media: typeof import('./src/views/changduan/media/index.vue')['default']
    WebSiteRadioGroup: typeof import('./src/components/WebSiteRadioGroup.vue')['default']
    ZimuConfig: typeof import('./src/components/ZimuConfig.vue')['default']
    ZimuLayer: typeof import('./src/views/ZimuLayer.vue')['default']
  }
}

export {}
